//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residus
    {
        public int Id { get; set; }
        public int Anyo { get; set; }
        public int MunicipioId { get; set; }
        public Nullable<double> MateriaOrganica { get; set; }
        public Nullable<double> PodaJardineria { get; set; }
        public Nullable<double> PaperCartro { get; set; }
        public Nullable<double> Vidre { get; set; }
    
        public virtual Municipios Municipios { get; set; }
    }
}
